"""B2 attacks on payroll exports: hours, duplicates, periods, totals rows, repeated headers."""
import pytest

from tests.breakers.edge_world import HR, NOISE, PAY, PAY_H, csv_text, run

HRS_OR_NOISE = NOISE | {"HRS-PAID-VS-SCHED"}


def _hours(values):
    rows = [list(r) for r in PAY]
    for r, v in zip(rows, values):
        r[6] = v
    return rows


def test_decimal_comma_hours_are_not_read_as_365(tmp_path, settings):
    """'36,5' (European decimal comma) became 365.0 with no parse issue."""
    r = run(tmp_path, settings, pay=_hours(["36,5", "40", "16", "24"]))
    assert [p["hours_paid"] for p in r.pay_periods("P-E201")] in ([36.5], [None]), r.pay_periods("P-E201")


def test_hours_with_unit_suffix_are_read(tmp_path, settings):
    """'40 hrs', '16h', '24 hours': the number is unambiguous; today they become NULL hours (LOW parse note)."""
    r = run(tmp_path, settings, pay=_hours(["36", "40 hrs", "16h", "24 hours"]))
    got = [r.pay_periods(p)[0]["hours_paid"] for p in ("P-E202", "P-E203", "P-E204")]
    assert got == [40.0, 16.0, 24.0], got


def test_impossible_weekly_hours_are_flagged_as_such(tmp_path, settings):
    """Negative, 0-with-shifts is fine, but > 168 h in a 7-day period is physically impossible."""
    r = run(tmp_path, settings, pay=_hours(["-8", "400", "1,036", "24"]))
    for pid in ("P-E201", "P-E202", "P-E203"):
        extra = [i for i in r.about(pid, *HRS_OR_NOISE)]
        assert extra, f"{pid}: impossible paid hours raised only HRS-PAID-VS-SCHED"


def test_missing_hours_is_flagged(tmp_path, settings):
    r = run(tmp_path, settings, pay=_hours(["", "40", "16", "24"]))
    assert r.about("P-E201", *HRS_OR_NOISE), "an empty hours_paid cell raised nothing and the hours check was skipped"


def test_zero_hours_with_scheduled_shifts_is_flagged(tmp_path, settings):
    r = run(tmp_path, settings, pay=_hours(["0", "40", "16", "24"]))
    assert [i.entity_ids for i in r.ids("HRS-PAID-VS-SCHED")] == [["P-E201"]]


def test_duplicate_payroll_row_same_id_does_not_crash(tmp_path, settings):
    """A payroll row exported twice (same payroll_id, same data) aborts the whole ingest with a DuckDB constraint error."""
    r = run(tmp_path, settings, pay=[*PAY, list(PAY[0])], raise_errors=False)
    assert r.error is None, repr(r.error)
    assert len(r.pay_periods("P-E201")) == 1


def test_conflicting_duplicate_payroll_id_does_not_crash(tmp_path, settings):
    bad = list(PAY[0])
    bad[6] = "20"
    r = run(tmp_path, settings, pay=[*PAY, bad], raise_errors=False)
    assert r.error is None, repr(r.error)
    assert r.about("P-E201", *NOISE), "same payroll_id with 36 vs 20 hours raised nothing"


def test_duplicate_period_with_new_payroll_id_is_flagged(tmp_path, settings):
    """Same person, same week, same hours under a new payroll_id: paid twice (72 h vs 36 h scheduled)."""
    dup = list(PAY[0])
    dup[0] = "P-3009"
    r = run(tmp_path, settings, pay=[*PAY, dup])
    assert len(r.pay_periods("P-E201")) == 1 or r.about("P-E201", *NOISE), "double pay for one week raised nothing"


def test_overlapping_pay_periods_are_flagged(tmp_path, settings):
    r = run(tmp_path, settings, pay=[*PAY, ["P-3010", "REYES, SOFIA", "RN", "BYS", "2026-09-17", "2026-09-23", "36"]])
    assert r.about("P-E201", *HRS_OR_NOISE), "overlapping pay periods raised nothing"


def test_period_end_before_period_start_is_flagged(tmp_path, settings):
    rows = [["P-3001", "REYES, SOFIA", "RN", "BYS", "2026-09-20", "2026-09-14", "36"], *PAY[1:]]
    r = run(tmp_path, settings, pay=rows)
    assert r.about("P-E201", *HRS_OR_NOISE), "period_end < period_start raised nothing (only the paid-vs-scheduled side effect)"


def test_month_long_pay_period_in_a_weekly_export_is_flagged(tmp_path, settings):
    rows = [["P-3001", "REYES, SOFIA", "RN", "BYS", "2026-09-14", "2026-10-14", "36"], *PAY[1:]]
    r = run(tmp_path, settings, pay=rows)
    assert r.about("P-E201", *NOISE), "a 31-day period in a weekly export raised nothing"


def test_payroll_person_missing_from_hr_is_flagged(tmp_path, settings):
    r = run(tmp_path, settings, pay=[*PAY, ["P-3011", "GHOST, GRACE", "RN", "BYS", "2026-09-14", "2026-09-20", "40"]])
    assert [i.severity for i in r.ids("PAY-NO-HR")] == ["HIGH"]


@pytest.mark.parametrize("junk", [
    ["TOTAL", "", "", "", "", "", "156"],
    ["TOTAL", "", "", "", "", "", "  1234"],
    ["Grand Total", "", "", "", "", "", "1,234.0"],
    ["Report generated by ADP 2026-09-21", "", "", "", "", "", ""],
    PAY_H,
], ids=["total", "total_spaces", "grand_total", "footer", "repeated_header"])
def test_totals_footer_or_repeated_header_row_in_payroll(tmp_path, settings, junk):
    """A footer/totals/repeated-header row must not abort the run and must not eat the real payroll rows."""
    r = run(tmp_path, settings, pay=None, pay_text=csv_text(PAY_H, [*PAY[:2], junk, *PAY[2:]]), raise_errors=False)
    assert r.error is None, repr(r.error)
    assert len(r.p.db.query("SELECT * FROM pay_periods WHERE person_id IS NOT NULL")) == 4
    assert len(r.persons) == 4


def test_payroll_row_with_blank_period_date_does_not_crash(tmp_path, settings):
    rows = [["P-3001", "REYES, SOFIA", "RN", "BYS", "", "", "36"], *PAY[1:]]
    r = run(tmp_path, settings, pay=rows, raise_errors=False)
    assert r.error is None, repr(r.error)


def test_unquoted_comma_in_payroll_name_is_not_remapped_as_hr(tmp_path, settings):
    """Hand-edited export: REYES, SOFIA without quotes gives 8 fields on a 7-column header."""
    text = ",".join(PAY_H) + "\n" + "\n".join(",".join(r) for r in PAY) + "\n"
    r = run(tmp_path, settings, pay=None, pay_text=text)
    templates = {m["template_id"] for m in r.p.db.query("SELECT m.template_id FROM mappings m JOIN raw_tables t USING (table_id) JOIN files f ON f.file_id = t.file_id WHERE f.file_name = 'payroll.csv'")}
    assert "hr_roster" not in templates, templates
    assert len(r.persons) == 4


def test_blank_rows_and_title_rows_in_payroll_are_skipped(tmp_path, settings):
    text = "Payroll Export - Harborview Care Group\nGenerated 2026-09-21\n" + csv_text(PAY_H, [PAY[0], [""] * 7, PAY[1], [" "] * 7, *PAY[2:]])
    r = run(tmp_path, settings, pay=None, pay_text=text)
    assert len(r.p.db.query("SELECT * FROM pay_periods")) == 4
